FROM rust:1.83-slim

# Install system dependencies
RUN apt-get update && \
    apt-get install -y \
      procps iproute2 \
      build-essential \
      libpq-dev \
      pkg-config \
      protobuf-compiler \
      curl \
      git \
      ca-certificates \
      nodejs \
      npm && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# Install additional Rust components
RUN rustup component add clippy rustfmt

# Install wasm target
RUN rustup target add wasm32-unknown-unknown

# Install cargo tools
RUN cargo install diesel_cli --no-default-features --features postgres --locked && \
    cargo install cargo-audit --locked && \
    cargo install cargo-outdated --locked

# Create non-root user and home
RUN useradd -m dev

# Create project directory with correct ownership
RUN mkdir /app && chown dev:dev /app

# Switch to dev user
USER dev

# Set default working directory for dev
WORKDIR /app

# Set default shell
CMD [ "bash" ]
