FROM rust:1.81-slim

# Install system dependencies
RUN apt-get update && \
    apt-get install -y \
      build-essential \
      libpq-dev \
      pkg-config \
      protobuf-compiler \
      curl \
      git \
      ca-certificates \
      nodejs \
      npm && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# Install additional Rust components
RUN rustup component add clippy rustfmt

# Install wasm target
RUN rustup target add wasm32-unknown-unknown

# Install cargo tools
RUN cargo install diesel_cli --no-default-features --features postgres --locked --release && \
    cargo install cargo-audit --locked --release && \
    cargo install cargo-outdated --locked --release

# Create a non-root user (optional)
RUN useradd -m dev
USER dev
WORKDIR /home/dev

# Default command
CMD [ "bash" ]
